### ISSUE TITLE
Git commit SHA on hex.pm

### ISSUE THREAD

**Issue by mgwidmann** [hexpm/hex_web#443] opened 2016-11-23 03:15 UTC
If possible it would be really nice to be able to see what commit went in specific versions. I've come across several packages that I was unsure if the merged PRs I need which were in hex.pm or not. A recorded SHA at time of publishing would help identify a version -> commit mapping for users.

**Comment by ericmj** [comment] 2016-11-23 10:20
It's hard to generalize something like this because git is not a requirement for hex so it would be hard for clients to know how to shell out to get the commit # for different version control systems.

I think it's best to ask package maintainers to push tags that match the published hex versions.

**Comment by mgwidmann** [comment] 2016-11-23 15:14
Yes, I understand. With so many packages though, and growing, asking everyone to be more organized isn't a full-proof solution. Do you think it'd be possible to just detect if its a git repo and add it then only? Failing silently when its not? 

I feel like it would make things easier on package maintainers, especially since the large majority (a very high percent) do use git from what I've seen.

**Comment by wojtekmach** [comment] 2016-11-23 17:07
@mgwidmann If we decide to support this, how would it work exactly? E.g. looking at Ecto [site](https://hex.pm/packages/ecto) and [api](https://hex.pm/api/packages/ecto), how would we display the SHA? As a string, or as a new item in links map? How would the user know to associate the SHA with where it's hosted & accessible? Currently, packages needn't be hosted anywhere, so we'd likely need to traverse `links` map (e.g.: `%{"GitHub" => "https://github.com/elixir-ecto/..."}`) or add a canonical scm url. 

I like this proposal but I think some stuff would have to be ironed out first. Even if we add it, I believe maintainers would still be occasionally asked by users to publish tags. Thus, perhaps it would be better to see if we can make it easier for maintainers to publish tags first? Afterwards, I'd be personally much more inclined to add first-class support for tags (similar to how exdoc can refer to [source_url/source_ref](https://github.com/elixir-ecto/ecto/blob/v2.0.5/mix.exs#L30)).

Perhaps someone could start a library that wraps `mix hex.publish` with some additional stuff mentioned above, see if it gets any traction, and then reconsider it here?

**Comment by mgwidmann** [comment] 2016-11-30 05:24
I've been making aliases for myself to get this to work in tandem. See here: https://github.com/mgwidmann/scrivener_html/blob/master/mix.exs#L65

Its just a bit annoying having to do it to every project...

I feel like this shouldn't be as hard as you've stated, so maybe I'm missing something. What I imagined was something as simple as:

```elixir
# Run during the `mix hex.publish` command
sha = if File.dir?(".git") do # maybe also check here if git is installed via `which git`?
        System.cmd("git", ["rev-parse", "HEAD"]) |> elem(0)
      end
# As a nice to have as well once the package is published:
System.cmd("git", ["tag", "-a", "v#{project.version}", "-m", "v#{project.version}"])
System.cmd("git", ["push", "--tags"])
```

Then for each release, if theres a `Github` link included with the project, simply combine the two:

```
links["Github"] <> "/commit/" <> sha
```

**Comment by ericmj** [comment] 2016-11-30 11:32
That's great, thank you @mgwidmann. It looks like we don't have to add anything to Hex at this time because it works with scripts.

> Its just a bit annoying having to do it to every project...

You can create a Hex package that adds this as task. The package can be installed as an archive or for as a dependency for each project you need it.

**Comment by mgwidmann** [comment] 2016-12-01 13:39
Yes, I could. It'd just be nice to have hex have that info as well to link commits with versions. For any unorganized project maintainer, its difficult to track down what code is in the version without explicitly opening the dependency in `deps` after running `mix deps.get` and digging through the code to find the feature you want.

Maintaining the project properly is one thing, if you'd prefer to keep that as a script like I have done I'd be ok with it. I'd just like to also see hex record the sha during publish (when available) and displayed on the site.

**Comment by mgwidmann** [comment] 2016-12-01 13:47
@wojtekmach to answer your question... Is there anything wrong with this?

```
{
  "url": "https://hex.pm/api/packages/ecto",
  "updated_at": "2016-11-24T21:20:40.044257Z",
  "releases": [
    {
      "version": "2.1.0-rc.4",
      "url": "https://hex.pm/api/packages/ecto/releases/2.1.0-rc.4",

      // Add this, this is just the recorded VCS value (from whatever system) that was
      // recorded during publishing. It would be up to (hex web or anyone using the API I guess)
      // to combine this with the links list to generate a link if possible to the source
      "commit": "abc123456789defhijklmnopqrstuvwxyz",

      "updated_at": "2016-11-16T22:14:39.825776Z",
      "inserted_at": "2016-11-16T22:14:28.742975Z"
    },
...
```

As far as hex is concerned its just metadata it records. It would be up to hex web to combine them if it also found a github link.

**Comment by mgwidmann** [comment] 2016-12-01 14:04
I don't know the codebase very well so this could be a bad spot but, I imagine this line:
https://github.com/hexpm/hex/blob/master/lib/mix/hex/build.ex#L54

Could look something like this instead:

```elixir
  defp meta_for(config, package, deps) do
    config
    |> Keyword.take([:app, :version, :elixir, :description])
    |> Enum.into(%{})
    |> Map.merge(package)
    |> package(config)
    |> Map.put(:requirements, deps)
    |> Map.put(:commit, vcs_commit())  # nil when not under git version control
  end

  defp vcs_commit() do
    # Just support GIT for now, if others come up as being necessary can add later
    if File.dir?(".git") && System.cmd("which", ["git"]) |> elem(0) != "" do
      System.cmd("git", ["rev-parse", "HEAD"]) |> elem(0)
    end
  end
```

I'm not sure if putting it into the `meta` data is the right spot or if that would allow it to show up like I showed above in the releases data, but this is the only thing I see as being necessary. Everything else discussed in this issue is a nice to have.

**Comment by ericmj** [comment] 2016-12-01 14:08
The problem is that the commit is not enough. What if they did not add the optional github link, having the commit does not help if there is no way to find the repo.

**Comment by mgwidmann** [comment] 2016-12-01 14:10
Yes true, and when thats noticed and fixed, adding the github link would then retroactively link it to the source (since the prior publishes recorded the sha).

**Comment by ericmj** [comment] 2016-12-01 15:16
I don't like that we have add a field to the metadata that is not strictly useful. If we add this then the uri to the source repo needs to be added to the metadata as well, instead of having it as unstructured (in the sense that we do not enforce a format) and optional link.

I think for now it's best to ask maintainers to tag their repos and if you can provide a tool that automates the tagging that would be very useful for the community.

**Comment by ericmj** [comment] 2016-12-01 15:17
In retrospect it would probably have been better to add the source repo uri directly to the metadata when we created Hex. But if we move it there now from the links I think we would have an even bigger mess on our hand.

**Comment by mgwidmann** [comment] 2016-12-01 18:48
😞 

I feel very strongly its Hex's job to tell us whats in each of these packages... Right now, it does not. If it means connecting hex with the source repository, I'd +1 that.

Like José always says, its about the tradeoffs. Being VCS agnostic has some benefit in that users are free to use any VCS system they please. However it has downsides as well, this being one of them. The key factor here is does a large majority of the packages use GIT for source control, and if so, being VCS agnostic has diminishing returns the smaller that number becomes. I feel like the number of packages under git source control is large enough to warrant integration. For the other packages under another VCS system, having an optional `git_url` field shouldn't cause Hex to operate any different than it does today.

Heres my suggestion: Leave the `Github` link, since thats a link to the website. Add a `git_url` to the metadata and when its present capture the commit SHA for every publish. I don't think we have very much to lose by adding that feature.

**Comment by josevalim** [comment] 2016-12-01 19:02
I have a different opinion here. A package does not need to come from any version control so it feels very weird to reference a particular version control source. A package may also have built artifacts by the time of publishing which are not versioned. I ultimately consider the package to be the source of truth, especially because it is immutable.

For example, if we employed this technique, many of the published Ecto packages would now have stale information, since the URL has changed from elixir-lang/ecto to elixir-ecto/ecto.

We could have this information somehow but to me it certainly does not feel to be an intrinsic part of a package.

**Comment by michalmuskala** [comment] 2016-12-01 19:21
Maybe a way to download the package content and examine it without adding to the project could help with this? A simple taks such as `mix hex.download package [-v version] [path]` that works similar, in a way, to `git clone repo`. This could help if someone wants to examine the code of the package and be sure that nothing will be actually running.

 I could also imagine an online file browser of the package's content. This could work both as something built-in or, at least initially, as an external service that downloads the packages from the registry and exposes them for introspection.

**Comment by sschneider1207** [comment] 2016-12-01 19:22
What about a SHA1 hash of the entire package as it is submitted to hex?  It's not something you could retrieve directly from GitHub's website, but you could calculate it from a clone to compare.

**Comment by josevalim** [comment] 2016-12-01 19:25
@sschneider1207 I am not exactly sure what you are proposing here. Hex does generate a checksum. How would it apply to the topic at hand?

**Comment by josevalim** [comment] 2016-12-01 19:28
> Maybe a way to download the package content and examine it without adding to the project could help with this?

To be honest, running deps.get is not going to execute any code, so you can easily rely on that. But there is also an issue in the hex repository about depending on local packages, on their `.tar` to be more precise, which would require the ability to build and download them in the first place.

**Comment by sschneider1207** [comment] 2016-12-01 19:28
@josevalim if the checksum is displayed on the hex page for a package I could compare it with a checksum I generated based on the master branch of a repo in order to determine if the version on hex is the master version.

**Comment by ferd** [comment] 2016-12-01 19:41
One of the thing we do with rebar3 and I believe Mix do is store down the hash of the package in the lock files for the project. If you build your project and inspect it, the lock file should prevent getting packages with a hash that changed in subsequent builds. This is hidden from the user and done automatically afaik.

To get an equivalent guarantee with a checksum or commit hash, you'd need to take the current version in your build, and then compare it with an independently built one.

I guess there is an implicit limitation in how much you trust the tools used to build your projects though.

**Comment by ericmj** [comment] 2016-12-01 20:24
@sschneider1207 We don't have a reproducible way to build packages so we can't ensure that checksum will be the same given the same source files, things like file timestamps would change it.

See https://github.com/hexpm/specifications/pull/4

**Comment by ericmj** [comment] 2016-12-01 20:25
If it would help we can add a link on the website to download the package tarball. Keep in mind that the package tarball has other things like the metadata file and some other files and the tarball with source files is nested inside the package tarball.

**Comment by mgwidmann** [comment] 2016-12-01 22:22
so heres a recent incident of mine where this was an issue:
https://github.com/gaynetdinov/ex_marshal/pull/12

**Comment by ericmj** [comment] 2016-12-01 22:48
That looks to be the reverse issue? I don't think we can do anything about if people forget to publish a hex version after tagging the release in git.

**Comment by mgwidmann** [comment] 2016-12-02 01:44
Sorry, yeah I was thinking of something else and I can't find it now... There was an issue I had where the tagged version was different from what was actually published. The commit SHA would have been particularly useful. Something like that doesn't have to happen on purpose.

I don't think publishing tags is a bad practice and it doesn't necessarily have to be something hex does for sure.

Seems everyone is against it except @wojtekmach who said he liked the proposal, so I'll let it go if you think this discussion is over with...

**Comment by wojtekmach** [comment] 2016-12-22 17:36
@mgwidmann we don't have plans to support this in the short term in Hex so I'll close this issue for now.

**Closed by wojtekmach** 2016-12-22 17:36 UTC

**Comment by wojtekmach** [comment] 2017-04-12 18:39
For anyone interested, I'm putting together a small tool (that can be installed as mix.archive) that automatically publishes git tags and does some rudimentary checks. See: https://github.com/wojtekmach/publish_plus

It can be extended further to check/store additional package metadata.
