### ISSUE TITLE
Attemping to modify a release after an hour returns a 500

### ISSUE THREAD

**Issue by tsloughter** [hexpm/hex_web#98] opened 2015-02-15 18:26 UTC
The response from the server to the client is just a 500. I see in the server logs: 

```2015-02-15 12:21:55.654 [error] ** (Poison.EncodeError) unable to encode value: {:created_at, "can only modify a release up to one hour after creation"}
```

It be nice to return a `40x` and the error to the client so a useful message can be given to the user.

**Comment by jcspencer** [comment] 2015-02-15 20:12
The problem lies [here](https://github.com/hexpm/hex_web/blob/master/lib/hex_web/api/router.ex#L226). 

We only seem to be checking for the `:ok` return type; but we should also be matching against `{:error, result}` to throw a 40x error and supply a useful error message to the client. This can be fixed by wrapping the existing code in a `case`, and matching both `:ok` and `{:error, reason}` return types.

To fix the Poison encoding error, we simply need to merge the returned keyword list into a serialisable map.

/cc @ericmj

**Comment by jcspencer** [comment] 2015-02-16 06:08
Note: the problem is now found [here](https://github.com/hexpm/hex_web/blob/master/lib/hex_web/api/router.ex#L246) on master.

**Comment by tsloughter** [comment] 2015-02-16 13:27
Is it only fixed for a delete? It also happens on a post to releases.

**Comment by ericmj** [comment] 2015-02-16 14:06
Fixed. We return 422 for all validation errors.

**Closed** 2015-02-16 14:06 UTC
