### ISSUE TITLE
Markdown rendering problem

### ISSUE THREAD

**Issue by hedgesky** [hexpm/hex_web#470] opened 2017-01-09 16:53 UTC
I've found a little problem with markdown rendering: on [this page](https://hexdocs.pm/timex/Timex.Format.DateTime.Formatters.Default.html) at the _Compound directives_ section several lines are rendered incorrectly. Here is [the source](https://github.com/bitwalker/timex/blob/3.1.7/lib/format/datetime/formatters/default.ex#L78) for them.

I think this is caused by inner issue in `earmark`. I've checked `earmark`'s master branch (not yet released), and the issue is solved there.

**Comment by wojtekmach** [comment] 2017-01-10 14:38
hex.pm/hexdocs.pm is only responsible for hosting the docs, and the problem is likely in `earmark` or `ex_dox` so I'm gonna close this issue.

I think you should be able to point `timex` to master version of `earmark` and if it solves the issue perhaps a patch will be accepted on timex to use in the meantime until a new version of earmark is released.

**Closed by wojtekmach** 2017-01-10 14:38 UTC
